#address-server-001
server:
  port: 8111
spring:
  application:
    name: address-server #应用程序名称，这个名字会注入到注册中心中,相同服务集群时名称一样，与访问路径无关，访问路径配置是server.servlet.context-path!
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:33061/cloud_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#数据交互配置
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mappers/*.xml

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址进行注册
    instance-id: address-server-8111 #在eureka中的服务别名，区别于spring.application.name
  client:
    service-url:
      defaultZone:  http://eureka8101.com:8101/eureka/,http://eureka8102.com:8102/eureka/,http://eureka8103.com:8103/eureka/

info: #在eureka中注册中心点击注册的服务别名（Status列）时跳转的页面信息，就是好看，没什么用
  server.name: address-server #服务名称
  server.port: 8111端口 #服务的端口
